name: biz_card_scanner
description: 名片掃描器 - Ollama AI + QR 分享
publish_to: 'none'
version: 1.3.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  qr_flutter: ^4.1.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  url_launcher: ^6.3.0
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
